table dCalendario
	lineageTag: b909d710-f98d-4fa1-baa4-a28c3d972878

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 387c4600-3802-4e3e-81d8-2a507af2ec20
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 1ef84a58-fdb4-4ca3-980b-59e059b981c2
			defaultHierarchy: LocalDateTable_73ceaa47-845b-46f5-8f09-d5d4d7d5aef3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: dd04e49f-b02d-47a6-9774-f34967532c77
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 79f09acf-d27b-47af-b4fa-ca47404dac5c
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Mes Abrev'
		dataType: string
		lineageTag: 92d5f5b9-693b-4568-a15b-392c44b26275
		summarizeBy: none
		sourceColumn: Mes Abrev
		sortByColumn: Mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 161cd4ea-eaf8-4419-a213-448d46277a06
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column MesAnoNum
		dataType: int64
		formatString: 0
		lineageTag: f2fff8b6-281f-48bf-b4d4-34ca6812ea44
		summarizeBy: sum
		sourceColumn: MesAnoNum

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source = ```
				let
				    // 1. Identificar Limites da Data na Fato
				    FonteDados = fCompras[Data_Pedido],
				    DataMinima = List.Min(FonteDados),
				    DataMaxima = List.Max(FonteDados),
				    
				    // 2. Ajustar para Inicio do Ano e Fim do Ano (Boas práticas)
				    DataInicio = Date.StartOfYear(DataMinima),
				    DataFim = Date.EndOfYear(DataMaxima),
				    
				    // 3. Gerar Lista de Datas
				    QtdeDias = Duration.Days(DataFim - DataInicio) + 1,
				    ListaDatas = List.Dates(DataInicio, QtdeDias, #duration(1, 0, 0, 0)),
				    
				    // 4. Converter para Tabela
				    Tabela = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"Date", type date}}),
				    
				    // 5. Adicionar Colunas de Análise
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Date]), Int64.Type),
				    #"Mes Inserido" = Table.AddColumn(#"Ano Inserido", "MesNum", each Date.Month([Date]), Int64.Type),
				    #"Nome Mes Inserido" = Table.AddColumn(#"Mes Inserido", "Mes", each Date.ToText([Date], "MMM", "pt-BR"), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome Mes Inserido", "Trimestre", each "T" & Number.ToText(Date.QuarterOfYear([Date])), type text),
				    
				    // 6. Coluna para Classificação (Sort by Column)
				    #"MesAno Inserido" = Table.AddColumn(#"Trimestre Inserido", "MesAnoNum", each [Ano] * 100 + [MesNum], Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"MesAno Inserido",{{"Mes", "Mes Abrev"}, {"MesNum", "Mes"}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Renamed Columns",{{"Mes Abrev", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

